name = "my-cloudflare-api"
main = "src/index.ts"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

[vars]
JWT_SECRET = "super-secret-video-studio-key-123456"

[[d1_databases]]
binding = "DB"
database_name = "new-website-db"
database_id = "af4db462-eece-493f-ad59-a91d1846f2df"
